name: Production Django deploy xaxa

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        source: "."
        target: "/home/user/backend/OnlineMarket"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        envs: DJANGO_SETTINGS_MODULE
        script_stop: true
        script: |
          git --work-tree=/home/user/backend/OnlineMarket --git-dir=/home/user/backend/OnlineMarket/.git clean -f .
          npm --prefix /home/user/backend/OnlineMarket install /home/user/backend/OnlineMarket
          pm2 restart onlinemarketapi
          sh /home/devops/deploy.sh "${{ github.event.head_commit.message }}" "Online Market"
